// ─── United States Profile Data ─────────────────────────────────────────────
// Auto-generated by parse_translate_us.py — DO NOT EDIT MANUALLY
// Stub file — will be replaced by the full dataset once translation completes.

export interface USTable {
  headers: { en: string; ro: string }[];
  rows: { en: string; ro: string }[][];
}

export interface USSubsection {
  heading: { en: string; ro: string };
  paragraphs: { en: string; ro: string }[];
}

export interface USSection {
  id: string;
  title: { en: string; ro: string };
  subsections: USSubsection[];
  tables: USTable[];
}

export const US_SECTIONS: USSection[] = [
  {
    id: "etymology-and-national-identity",
    title: { en: "Etymology and National Identity", ro: "Etimologie și Identitate Națională" },
    subsections: [
      {
        heading: { en: "Origin of the Name", ro: "Originea Numelui" },
        paragraphs: [
          {
            en: "The name \"United States of America\" emerged during the American Revolution. In 1775, the Second Continental Congress referred to the colonies as \"United Colonies\" in early documents. The Declaration of Independence (July 4, 1776) used \"the thirteen united States of America.\" On September 9, 1776, Congress officially adopted \"United States of America\" to replace \"United Colonies.\" The Articles of Confederation (ratified 1781) formalized it in Article I, and the 1787 Constitution retained the name, emphasizing the union of states.",
            ro: "Numele 'Statele Unite ale Americii\" a apărut în timpul Revoluției Americane. În 1775, cel de-al Doilea Congres Continental se referea la colonii ca 'Colonii Unite\" în documentele timpurii. Declarația de Independență (4 iulie 1776) folosea expresia 'cele treisprezece state unite ale Americii.\" Pe 9 septembrie 1776, Congresul a adoptat oficial 'Statele Unite ale Americii\" pentru a înlocui 'Coloniile Unite.\" Articolele Confederației (ratificate în 1781) au formalizat acest lucru în Articolul I, iar Constituția din 1787 a păstrat denumirea, subliniind uniunea statelor.",
          },
        ],
      },
      {
        heading: { en: "Founding Symbols and Iconography", ro: "Simboluri Fondatoare și Iconografie" },
        paragraphs: [
          {
            en: "The Great Seal of the United States, adopted by the Continental Congress on June 20, 1782, features a bald eagle as its central emblem, symbolizing national sovereignty and strength. Secretary Charles Thomson devised the final design, incorporating an eagle with wings displayed, clutching an olive branch in its right talon representing peaceful intentions and a bundle of 13 arrows in its left signifying readiness for defense.",
            ro: "Marele Sigiliu al Statelor Unite, adoptat de Congresul Continental pe 20 iunie 1782, are ca element central un vultur pleșuv, simbolizând suveranitatea națională și puterea. Secretarul Charles Thomson a conceput designul final, incorporând un vultur cu aripile desfășurate, ținând în talpa dreaptă o ramură de măslin reprezentând intențiile pașnice și un fascicul de 13 săgeți în stânga, semnificând disponibilitatea pentru apărare.",
          },
          {
            en: "The Flag of the United States, officially resolved by Congress on June 14, 1777, consists of 13 horizontal red and white stripes and 13 stars arranged in a circle on a blue field, directly representing the union of the original 13 states.",
            ro: "Steagul Statelor Unite, adoptat oficial de Congres pe 14 iunie 1777, constă din 13 dungi orizontale roșii și albe și 13 stele aranjate în cerc pe un câmp albastru, reprezentând direct uniunea celor 13 state originale.",
          },
        ],
      },
    ],
    tables: [],
  },
  {
    id: "history",
    title: { en: "History", ro: "Istorie" },
    subsections: [
      {
        heading: { en: "Pre-Columbian Civilizations and Indigenous Societies", ro: "Civilizații Pre-Columbiene și Societăți Indigene" },
        paragraphs: [
          {
            en: "Indigenous societies in North America before 1492 ranged from nomadic hunter-gatherers in arid and northern regions to settled agricultural communities in fertile river valleys and coastal areas. Population estimates for the area north of Mesoamerica range from 2 million to 18 million.",
            ro: "Societățile indigene din America de Nord înainte de 1492 variau de la vânători-culegători nomazi în regiunile aride și nordice până la comunități agricole sedentare în văile fertile ale râurilor și în zonele de coastă. Estimările populației pentru zona din nordul Mesoamericii variază de la 2 milioane la 18 milioane.",
          },
        ],
      },
      {
        heading: { en: "American Revolution and Constitutional Founding", ro: "Revoluția Americană și Fondarea Constituțională" },
        paragraphs: [
          {
            en: "The American Revolution (1775–1783) was driven by colonial opposition to British taxation and political control. The Declaration of Independence, adopted July 4, 1776, proclaimed natural rights and self-governance. The Constitution, ratified in 1788, established the federal republic with separation of powers and the Bill of Rights (1791) guaranteed civil liberties.",
            ro: "Revoluția Americană (1775–1783) a fost determinată de opoziția colonială față de impozitarea britanică și controlul politic. Declarația de Independență, adoptată la 4 iulie 1776, a proclamat drepturile naturale și autoguvernarea. Constituția, ratificată în 1788, a stabilit republica federală cu separarea puterilor, iar Carta Drepturilor (1791) a garantat libertățile civile.",
          },
        ],
      },
    ],
    tables: [],
  },
  {
    id: "geography-and-environment",
    title: { en: "Geography and Environment", ro: "Geografie și Mediu" },
    subsections: [
      {
        heading: { en: "Physical Landscape and Borders", ro: "Peisaj Fizic și Frontiere" },
        paragraphs: [
          {
            en: "The United States is the third-largest country by total area, spanning 9.834 million km². It borders Canada to the north, Mexico to the south, the Atlantic Ocean to the east, and the Pacific Ocean to the west. The terrain ranges from arctic tundra in Alaska to tropical rainforests in Hawaii and subtropical wetlands in Florida.",
            ro: "Statele Unite sunt a treia cea mai mare țară ca suprafață totală, acoperind 9,834 milioane km². Se învecinează cu Canada la nord, Mexic la sud, Oceanul Atlantic la est și Oceanul Pacific la vest. Relieful variază de la tundra arctică din Alaska la pădurile tropicale umede din Hawaii și zonele umede subtropicale din Florida.",
          },
        ],
      },
    ],
    tables: [],
  },
  {
    id: "government-and-law",
    title: { en: "Government and Law", ro: "Guvern și Lege" },
    subsections: [
      {
        heading: { en: "Constitutional Framework and Federalism", ro: "Cadru Constituțional și Federalism" },
        paragraphs: [
          {
            en: "The United States operates under a federal presidential constitutional republic. Power is divided between three branches — executive (President), legislative (Congress: Senate and House of Representatives), and judicial (Supreme Court and federal courts) — with checks and balances preventing concentration of authority.",
            ro: "Statele Unite funcționează ca o republică federală prezidențială constituțională. Puterea este împărțită între trei ramuri — executivă (Președintele), legislativă (Congresul: Senatul și Camera Reprezentanților) și judiciară (Curtea Supremă și instanțele federale) — cu frâne și contrabalanțe care previn concentrarea autorității.",
          },
        ],
      },
    ],
    tables: [],
  },
  {
    id: "foreign-relations-and-national-security",
    title: { en: "Foreign Relations and National Security", ro: "Relații Externe și Securitate Națională" },
    subsections: [
      {
        heading: { en: "Military Structure, Capabilities, and Expenditures", ro: "Structura Militară, Capacități și Cheltuieli" },
        paragraphs: [
          {
            en: "The United States maintains the world's most powerful military, with a 2024 defense budget of approximately $954 billion — nearly three times that of China, the second-largest spender. The military comprises six branches: Army, Navy, Marine Corps, Air Force, Space Force, and Coast Guard, with approximately 1.3 million active-duty personnel.",
            ro: "Statele Unite mențin cea mai puternică forță militară din lume, cu un buget de apărare pentru 2024 de aproximativ 954 de miliarde de dolari — aproape de trei ori mai mult decât al Chinei, al doilea cel mai mare cheltuitor. Forțele militare cuprind șase ramuri: Armata, Marina, Corpul Pușcașilor Marini, Forțele Aeriene, Forța Spațială și Garda de Coastă, cu aproximativ 1,3 milioane de militari activi.",
          },
        ],
      },
    ],
    tables: [],
  },
  {
    id: "economy",
    title: { en: "Economy", ro: "Economie" },
    subsections: [
      {
        heading: { en: "Capitalist Foundations and Market Dynamics", ro: "Fundamente Capitaliste și Dinamici de Piață" },
        paragraphs: [
          {
            en: "The United States economy rests on capitalist principles of private property rights, voluntary exchange, and limited government intervention. With a nominal GDP of approximately $28.8 trillion in 2024, it is the world's largest national economy. The US dollar serves as the primary global reserve currency, representing approximately 58% of global foreign exchange reserves.",
            ro: "Economia Statelor Unite se bazează pe principiile capitaliste ale drepturilor de proprietate privată, schimbului voluntar și intervenției guvernamentale limitate. Cu un PIB nominal de aproximativ 28,8 trilioane de dolari în 2024, este cea mai mare economie națională din lume. Dolarul american servește ca principala monedă de rezervă globală, reprezentând aproximativ 58% din rezervele globale de schimb valutar.",
          },
        ],
      },
    ],
    tables: [],
  },
  {
    id: "demographics-and-society",
    title: { en: "Demographics and Society", ro: "Demografie și Societate" },
    subsections: [
      {
        heading: { en: "Population Size, Growth, and Density", ro: "Dimensiunea Populației, Creștere și Densitate" },
        paragraphs: [
          {
            en: "The United States is the third most populous country, with approximately 340 million people as of 2024. The population has grown from 3.9 million at the first census in 1790 to its current size, driven by natural increase and immigration. The US accepts more legal immigrants than any other country, averaging about 1 million per year.",
            ro: "Statele Unite sunt a treia cea mai populată țară, cu aproximativ 340 de milioane de oameni la nivelul anului 2024. Populația a crescut de la 3,9 milioane la primul recensământ din 1790 la dimensiunea actuală, determinată de creșterea naturală și imigrare. SUA acceptă mai mulți imigranți legali decât orice altă țară, cu o medie de aproximativ 1 milion pe an.",
          },
        ],
      },
    ],
    tables: [
      {
        headers: [
          { en: "Racial/Ethnic Group", ro: "Grup Rasial/Etnic" },
          { en: "Percentage", ro: "Procentaj" },
        ],
        rows: [
          [{ en: "White (Non-Hispanic)", ro: "Alb (Non-Hispanic)" }, { en: "59.3%", ro: "59,3%" }],
          [{ en: "Hispanic or Latino", ro: "Hispanic sau Latino" }, { en: "18.9%", ro: "18,9%" }],
          [{ en: "Black or African American", ro: "Negru sau Afro-American" }, { en: "13.6%", ro: "13,6%" }],
          [{ en: "Asian", ro: "Asian" }, { en: "6.3%", ro: "6,3%" }],
          [{ en: "Multiracial", ro: "Multirasal" }, { en: "2.9%", ro: "2,9%" }],
          [{ en: "Other", ro: "Altele" }, { en: "~1%", ro: "~1%" }],
        ],
      },
    ],
  },
  {
    id: "culture-and-values",
    title: { en: "Culture and Values", ro: "Cultură și Valori" },
    subsections: [
      {
        heading: { en: "Core Principles: Liberty, Individualism, and Exceptionalism", ro: "Principii de Bază: Libertate, Individualism și Excepționalism" },
        paragraphs: [
          {
            en: "American culture centers on several foundational values: individual liberty, equality of opportunity, self-reliance, democracy, and the rule of law. The concept of American Exceptionalism — the belief that the US has a unique mission in the world — has shaped foreign policy and national identity since the founding. Popular culture exported through Hollywood, music, and brands has made American culture a dominant global force.",
            ro: "Cultura americană se centrează pe câteva valori fundamentale: libertatea individuală, egalitatea de șanse, auto-suficiența, democrația și statul de drept. Conceptul de Excepționalism American — credința că SUA au o misiune unică în lume — a modelat politica externă și identitatea națională de la fondare. Cultura populară exportată prin Hollywood, muzică și branduri a făcut din cultura americană o forță globală dominantă.",
          },
        ],
      },
    ],
    tables: [],
  },
  {
    id: "controversies-and-debates",
    title: { en: "Controversies and Debates", ro: "Controverse și Dezbateri" },
    subsections: [
      {
        heading: { en: "Cultural Wars: Identity Politics and Traditional Values", ro: "Războaie Culturale: Politica Identității și Valorile Tradiționale" },
        paragraphs: [
          {
            en: "American society is marked by ongoing cultural debates between progressive and conservative visions. These include tensions around race and diversity, religious freedom versus secular governance, gun rights, immigration policy, and the role of government in social life. These fault lines have intensified political polarization, particularly since the 1990s.",
            ro: "Societatea americană este marcată de dezbateri culturale continue între viziunile progresiste și conservatoare. Acestea includ tensiuni legate de rasă și diversitate, libertatea religioasă versus guvernarea seculară, dreptul la arme, politica de imigrare și rolul guvernului în viața socială. Aceste linii de fractură au intensificat polarizarea politică, în special din anii 1990.",
          },
        ],
      },
    ],
    tables: [],
  },
];

export const US_QUICK_FACTS: { label: { en: string; ro: string }; value: { en: string; ro: string } }[] = [
  { label: { en: "Official Name", ro: "Denumire Oficială" }, value: { en: "United States of America", ro: "Statele Unite ale Americii" } },
  { label: { en: "Capital", ro: "Capitală" }, value: { en: "Washington, D.C.", ro: "Washington, D.C." } },
  { label: { en: "Largest City", ro: "Cel Mai Mare Oraș" }, value: { en: "New York City", ro: "New York City" } },
  { label: { en: "Government", ro: "Sistem de Guvernare" }, value: { en: "Federal Presidential Constitutional Republic", ro: "Republică Federală Prezidențială Constituțională" } },
  { label: { en: "Population", ro: "Populație" }, value: { en: "~340 million (2024)", ro: "~340 milioane (2024)" } },
  { label: { en: "Area", ro: "Suprafață" }, value: { en: "9.834 million km² (3rd largest)", ro: "9,834 milioane km² (locul 3 ca mărime)" } },
  { label: { en: "GDP (Nominal)", ro: "PIB (Nominal)" }, value: { en: "$28.8 trillion (2024) — World's largest", ro: "28,8 trilioane USD (2024) — Cea mai mare din lume" } },
  { label: { en: "Currency", ro: "Monedă" }, value: { en: "US Dollar (USD)", ro: "Dolarul american (USD)" } },
  { label: { en: "Official Language", ro: "Limbă Oficială" }, value: { en: "English (de facto)", ro: "Engleza (de facto)" } },
  { label: { en: "National Motto", ro: "Motto Național" }, value: { en: "\"In God We Trust\" (official since 1956)", ro: "\"In God We Trust\" (oficial din 1956)" } },
  { label: { en: "National Anthem", ro: "Imn Național" }, value: { en: "The Star-Spangled Banner", ro: "The Star-Spangled Banner" } },
  { label: { en: "Independence", ro: "Independența" }, value: { en: "July 4, 1776 (from Great Britain)", ro: "4 iulie 1776 (față de Marea Britanie)" } },
  { label: { en: "Constitution Adopted", ro: "Constituția Adoptată" }, value: { en: "September 17, 1787", ro: "17 septembrie 1787" } },
  { label: { en: "States", ro: "State" }, value: { en: "50 states + DC + territories", ro: "50 de state + DC + teritorii" } },
  { label: { en: "Military Budget", ro: "Buget Militar" }, value: { en: "$954 billion (2024) — World's largest", ro: "954 miliarde USD (2024) — Cel mai mare din lume" } },
  { label: { en: "Nobel Prizes", ro: "Premii Nobel" }, value: { en: "~400 (most of any country)", ro: "~400 (cel mai mult din orice țară)" } },
  { label: { en: "Life Expectancy", ro: "Speranța de Viață" }, value: { en: "76.4 years (2022)", ro: "76,4 ani (2022)" } },
];
