#!/usr/bin/env python3
"""Emit lib/data/shield-geometry.ts — the shield vector data used to draw the
map badges as NATIVE SVG (not <img>/foreignObject).

Map badges live inside the zoomable/pannable SVG group. HTML content in a
<foreignObject> does not track SVG transforms smoothly in Chrome/Safari, so the
badges jittered ("went haywire") on zoom and select. Drawing them as plain SVG
paths — the same primitive the roads use — makes them transform perfectly.

The geometry is shared: one narrow shell (1-2 digit, 601 wide) and one wide shell
(3-digit, 750 wide), the "INTERSTATE" legend, and the ten Roadgeek Series D digit
glyphs. The React side composes any number from these at runtime, matching the
static shield files exactly.
"""
import re, json, os

SHIELD_DIR = "public/interstate-shields"


def read(fn):
    return open(os.path.join(SHIELD_DIR, fn), encoding="utf-8").read()


def attr(tag, name):
    m = re.search(r'\b%s="([^"]+)"' % name, tag)
    return m.group(1) if m else None


# ── Ten digit glyphs (Roadgeek Series D) from the single-digit shields ─────────
from svgpathtools import parse_path

glyphs = {}
for n in range(10):
    for tag in re.findall(r"<path\b[^>]*>", read("I-%d.svg" % n)):
        if "Series D" in tag:
            d = attr(tag, "d")
            xmin, xmax, _, _ = parse_path(d).bbox()
            glyphs[str(n)] = {"d": d, "xmin": round(xmin, 3), "w": round(xmax - xmin, 3)}
            break

# ── Narrow shell (1-2 digit, 601×601) from a single-digit shield ───────────────
s5 = read("I-5.svg")
outline = re.search(r'<path id="a"[^>]*d="([^"]+)"', s5).group(1)
white_tf = re.search(r'<g fill="#fff"[^>]*transform="([^"]+)"', s5).group(1)
blue_n = re.search(r'<path fill="#003f87"[^>]*d="([^"]+)"', s5).group(1)
red_n = re.search(r'<path fill="#af1e2d"[^>]*d="([^"]+)"', s5).group(1)
banner_n_d = next(attr(t, "d") for t in re.findall(r"<path\b[^>]*>", s5) if "Series C" in t)

NARROW_SHAPE = (
    '<path d="%s" fill="#fff" stroke="#000" stroke-width="1" transform="%s"/>'
    '<path d="%s" fill="#003f87"/>'
    '<path d="%s" fill="#af1e2d"/>'
) % (outline, white_tf, blue_n, red_n)
NARROW_BANNER = '<path d="%s" fill="#fff"/>' % banner_n_d  # centred at x≈300

# Recentre the same banner onto the wide shell (300 → 375).
bx0, bx1, _, _ = parse_path(banner_n_d).bbox()
WIDE_BANNER = '<path d="%s" fill="#fff" transform="translate(%.3f,0)"/>' % (
    banner_n_d,
    375.0 - (bx0 + bx1) / 2,
)

# ── Wide shell (3-digit, 750×601) from the I-135 template ──────────────────────
t135 = read("I-135.svg")


def group(gid):
    return re.search(r'<g\b[^>]*id="%s".*?</g>' % gid, t135, re.DOTALL).group(0)


WIDE_SHAPE = group("g5") + group("g11") + group("g15")

ts = (
    "// AUTO-GENERATED by scripts/emit-shield-geometry.py — do not edit by hand.\n"
    "// Vector data for drawing Interstate shields as native SVG on the map.\n\n"
    "export interface Glyph { d: string; xmin: number; w: number; }\n\n"
    "export const GLYPHS: Record<string, Glyph> = %s;\n\n"
    "export const NARROW_SHAPE = %s;\n"
    "export const NARROW_BANNER = %s;\n"
    "export const WIDE_SHAPE = %s;\n"
    "export const WIDE_BANNER = %s;\n"
) % (
    json.dumps(glyphs, separators=(",", ":")),
    json.dumps(NARROW_SHAPE),
    json.dumps(NARROW_BANNER),
    json.dumps(WIDE_SHAPE),
    json.dumps(WIDE_BANNER),
)

out = "lib/data/shield-geometry.ts"
open(out, "w", encoding="utf-8").write(ts)
print("wrote %s (%d bytes)" % (out, len(ts)))
